<footer class="page-footer brown darken-3">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Junte-se ao CatBag!</h5>
                <a href="entrar.php" class="grey-text text-lighten-4">Cadastre-se agora!</a>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Saiba Mais</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="termos.php">Termos de uso</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright brown darken-4">
            <div class="container">
            © CatBag 2016 | PinheiroZeroOito Inc.
            </div>
          </div>
        </footer>
