<header>
    <div class="container">
    <img src="img/Logo_small.png" alt="Banner" title="CatBag - Melhorando o seu dia!">
    </div>
    
     <nav>
    <div class="nav-wrapper brown darken-4">
    <div class="container">
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><a href="index.php">HOME</a></li>
        <li><a href="catline.php">CATLINE</a></li>
        <li><a href="entrar.php">CONTA</a></li>
        <li>
            <form action="http://google.com/search">
                <input type="search" name="q" placeholder="Pesquisar...">
                
            </form></li>
      </ul>
      </div>
    </div>
  </nav>

</header>

