<header>
    <img src="img/Logo_small.png" alt="Banner" title="CatBag - Melhorando o seu dia!">
    <nav id="menu">
            <ul>
                <li class="itemMenu"><a href="index.php">HOME</a></li>
                
                <li class="itemMenu"><a href="catline.php">CATLINE</a></li>
                
                <li class="itemMenu" class="menuconta"><a href="conta.php">CONTA</a></li> <!-- Caso usuario esteja logado aparecera o nome de usuario -->
                
                <li class="itemBusca" class="busca">
                                <form action="http://google.com/search">
                                    <input type="search" name="q" placeholder="Pesquisar...">
                                    <input type="submit" value="Meow!">
                                </form></li>
            </ul>        
    </nav>
</header>

