<nav id="menu">
            <ul>
                <li class="itemMenu"><a href="#">HOME</a></li>
                
                <li class="itemMenu"><a href="#">CATLINE</a></li>
                
                <li class="itemMenu" class="menuconta"><a href="#">CONTA</a></li> <!-- Caso usuario esteja logado aparecera o nome de usuario -->
                
                <li class="itemMenu" class="busca">
                                <form action="http://google.com/search">
                                    <input type="search" name="q" placeholder="Pesquisar...">
                                    <input type="submit" value="Meow!">
                                </form></li>
            </ul>        
</nav>