<nav id="menu">
            <ul>
                <li><a href="#">HOME</a></li>
                
                <li><a href="#">CATLINE</a></li>
                
                <li><a href="#">CONTA</a></li> <!-- Caso usuario esteja logado aparecera o nome de usuario -->
                
                <li>
                                <form action="http://google.com/search">
                                    <input type="search" name="q" placeholder="Pesquisar...">
                                    <input type="submit" value="Meow!">
                                </form></li>
            </ul>        
</nav>